# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'thin'
gem 'rack'
gem 'hoodoo'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'json_spec'
end